### ISSUE TITLE
Have error KeyError: 'BOT_TOKEN' when try to deploy

### ISSUE THREAD

**Issue by Jaammerr** [mujadmani/Easy-Telegram-Airdrop-Bot#3]
Full error: 
Traceback (most recent call last):
File "/home/Jammer12/airdrop/bot.py", line 26, in
BOT_TOKEN = os.environ["BOT_TOKEN"]
File "/usr/local/lib/python3.9/os.py", line 679, in __getitem__
raise KeyError(key) from None
KeyError: 'BOT_TOKEN'

Mb anybody know, how to fix it?

**Comment by mujadmani** [comment]
Did you go here: https://telegram.me/BotFather and get the bot token?
